### PR TITLE
Add optional parsing of MeSH subheadings

### PR DESCRIPTION
**Pull request by raypereda**
Currently, the parser returns the major MeSH headings.
For example: 
```
<MeshHeading>
	<DescriptorName MajorTopicYN="N" UI="D001993">Bronchodilator Agents</DescriptorName>
	<QualifierName MajorTopicYN="Y" UI="Q000008">administration &amp; dosage</QualifierName>
	<QualifierName MajorTopicYN="N" UI="Q000009">adverse effects</QualifierName>
</MeshHeading>
```
The goal is to return the two QualifierName elements, which represent subheadings.

### CODE REVIEW

**Comment by titipata** [comment]
Sounds great to me. Should I merge this issue for adding the data or you are working on the parser on the PR?

**Comment by raypereda-gr** [comment]
@nicholasjuncos showed me a cool website for generating test PubMed XML files given a list of PubMed IDs.
https://pubmed2xl.com/xml/
That's how `data/pubmed-29768149.xml` was generated.

**Review by titipata — APPROVED** [review]
LGTM. Let me know if it's ready to be merged!

**Comment by raypereda-gr** [comment]
Will let you know next week. Using the new code may turn up a tweak.

**Comment by DustinHolden** [comment]
With little refactoring, I think we could eliminate the use of the `global` function swapping to make this more readable and maintainable. Happy to fork and do the refactoring.

**Comment by titipata** [comment]
@DustinHolden maybe you can coordinate with @raypereda and then I can merge once it's done?

**Comment by DustinHolden** [comment]
Can do, I'll coordinate with @raypereda . Thanks!

**Comment by raypereda** [comment]
This PR is done. @titipata Please merge.

**Pull request merged**
