### PR TITLE
[pubmed oa] Parse conflict of interest statements

### PR DESCRIPTION
**Pull request by simonwoerpel**
Hey, for a project i am involved i need to parse the statements about possible conflict of interests the authors / journals publish. Here is a work-in-progress approach that fulfills my basic needs for now, but I am happy for a discussion on how to improve this.

### CODE REVIEW

**Comment by titipata** [comment]
@simonwoerpel, this looks good to me! Maybe you can also add an example to `tests` and then I can merge this?

**Comment by simonwoerpel** [comment]
Sure I can, but I was not sure if this is already "enough" or if we should look a bit closer into the structure of how these statements are defined in the xml. And I didn't even investigate if there are more xpaths that contain possible statements. Thus, my solution here feels a bit hacky in just yielding everything into one string... that's why I opened this as a WIP for further discussion :see_no_evil:

**Comment by simonwoerpel** [comment]
I will continue hacking on this and maybe add a few more commits.

**Comment by titipata** [comment]
@simonwoerpel that's no worry! Yeah, if you can do a bit of testing, that would be awesome!

**Comment by titipata** [comment]
@simonwoerpel, should I merge this PR first or should I wait for a bit? Thanks!!

**Comment by simonwoerpel** [comment]
hey, i will do some improvements about the coi parsing this week and then go for merge! thanks for the patience. :slightly_smiling_face:

**Comment by titipata** [comment]
Thanks for the follow-up! I can check it right after you're done. Thank you!

**Comment by simonwoerpel** [comment]
ok i had a more closer look at it now, found some more xpaths that can contain possible conflict of interest statements, and added a line to the test in `tests/test_pubmed_oa_parser.py`

looks good for me now! :slightly_smiling_face:

**Comment by titipata** [comment]
Woohoo! This looks good!

**Pull request merged**
